### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by Coot302** [NoobMCBG/KillDeathSound#2]
THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: KillDeathSound

Error: foreach() argument must be of type array|object, string given
File: plugins/KillDeathSound_dev-67.phar/src/NoobMCBG/KillDeathSound/KillDeathSound
Line: 99

**Comment by NoobMCBG** [comment]
You can delete the old plugin_data of KillDeathSound
