### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xodamcm** [NoobMCBG/KillDeathSound#6]
:41:35 UTC 2022

PocketMine-MP version: 4.3.2 [Protocol 503]
Git commit: 755ca1af9b1b69226a6ed4597dc947aeec8088fe
PHP version: 8.0.17
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: KillDeathSound

Error: Call to a member function getPosition() on null
File: plugins/KillDeathSound_dev-78.phar/src/NoobMCBG/KillDeathSound/KillDeathSound
Line: 82
Type: Error
Backtrace:
#0 pmsrc/src/event/RegisteredListener(75): NoobMCBG\KillDeathSound\KillDeathSound->onDeath(object pocketmine\event\player\PlayerDeathEvent#275547)
#1 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerDeathEvent#275547)
#2 pmsrc/src/player/Player(2207): pocketmine\event\Event->call()
#3 pmsrc/src/entity/Entity(553): pocketmine\player\Player->onDeath()
#4 plugins/AntiCombatLog_v1.0.0.phar/src/Electro/AntiCombatLog/AntiCombatLog(83): pocketmine\entity\Entity->kill()
#5 pmsrc/src/event/RegisteredListener(75): Electro\AntiCombatLog\AntiCombatLog->onQuit(object pocketmine\event\player\PlayerQuitEvent#179822)
#6 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerQuitEvent#179822)
#7 pmsrc/src/player/Player(2094): pocketmine\event\Event->call()
#8 pmsrc/src/network/mcpe/NetworkSession(582): pocketmine\player\Player->onPostDisconnect(string[17] client disconnect, NULL )
#9 pmsrc/src/network/mcpe/NetworkSession(515): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
#10 pmsrc/src/network/mcpe/NetworkSession(584): pocketmine\network\mcpe\NetworkSession->tryDisconnect(object Closure#360062, string[17] client disconnect)
#11 pmsrc/src/network/mcpe/raklib/RakLibInterface(151): pocketmine\network\mcpe\NetworkSession->onClientDisconnect(string[17] client disconnect)
#12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(75): pocketmine\network\mcpe\raklib\RakLibInterface->onClientDisconnect(integer 6, string[17] client disconnect)
#13 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#94731)
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#16 pmsrc/src/Server(1661): pocketmine\snooze\SleeperHandler->sleepUntil(double 1652542895.8927)
#17 pmsrc/src/Server(1047): pocketmine\Server->tickProcessor()
#18 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#19 pmsrc/src/PocketMine(327): pocketmine\server()
#20 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[73] 			            	$volume = $this->getConfig()->getAll()["kill"]["volume"];
[74] 			            	$pitch = $this->getConfig()->getAll()["kill"]["pitch"];
[75] 				   	foreach($this->getConfig()->getAll()["kill"]["sound"] as $soundName){
[76] 			    			$this->playSound($damager, $soundName, $volume, $pitch);
[77] 					}
[78] 				}
[79] 			}
[80] 			if($this->getConfig()->getAll()["kill"]["blood"] == true){
[81] 				if($this->getConfig()->getAll()["kill"]["blood-all-entity"] == true){
[82] 					$this->addBlood($damager->getPosition());
[83] 				}else{
[84] 					if($damager instanceof Player){
[85] 						$this->addBlood($damager->getPosition());
[86] 					}
[87] 				}
[88] 			}
[89] 		}
[90] 	}
[91]     
[92]         /**

**Comment by NoobMCBG** [comment]
You use dev-78
Please use dev-82
